=begin
#Recurring Payments Merchant API

## Recurring payments Recurring payments is used for subscription payments such as weekly dues for newspaper access, monthly dues for public transportation, etc. 1. A draft agreement is initialized and the user is redirected for approval. 2. The user approves the agreement and the merchant can call GET on the agreement to verify the status. 3. The merchant can start sending charges which will be charged the user in the future. The merchant is responsible for checking the status of charges, and cancelling any user access if charges are failing (or contacting the user). ## Authentication See <a href=\"#/Access%20Controller/getAccessToken\" target=\"_blank\">Get Access Token</a> For information regarding authentication please read [our guide](https://github.com/vippsas/vipps-recurring-api/blob/master/vipps-recurring-api.md#authentication-and-authorization---api-access-token)

The version of the OpenAPI document: 2.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1-SNAPSHOT

=end

require 'date'
require 'time'

module VippsRecurring
  class AgreementRequest
    attr_accessor :campaign

    attr_accessor :currency

    # Customers phone number (if available). Used to simplify the following Vipps interaction. MSISDN: https://www.msisdn.org
    attr_accessor :customer_phone_number

    attr_accessor :initial_charge

    attr_accessor :interval

    # Number of intervals between charges. Example: interval=week, intervalCount=2 to be able to charge every two weeks. Charges should occur at least once a year
    attr_accessor :interval_count

    # If merchant is redirecting user from an app or a mobile device.
    attr_accessor :is_app

    # URL where Vipps can send the customer to view/manage their subscription. Typically a \"My page\" where the user can change, pause, cancel, etc. We recommend letting users logg inn with Vipps, not with username and password.
    attr_accessor :merchant_agreement_url

    # URL where customer should be redirected after the agreement has been approved/rejected in the Vipps mobile application.
    attr_accessor :merchant_redirect_url

    # Treated as a whole sum postfixed with two decimals for cents, eg 234 = 2.34 NOK
    attr_accessor :price

    # Product name (short)
    attr_accessor :product_name

    # Product description (longer)
    attr_accessor :product_description

    # Space separated list of the user profile-data scopes to require for the agreement.
    attr_accessor :scope

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'campaign' => :'campaign',
        :'currency' => :'currency',
        :'customer_phone_number' => :'customerPhoneNumber',
        :'initial_charge' => :'initialCharge',
        :'interval' => :'interval',
        :'interval_count' => :'intervalCount',
        :'is_app' => :'isApp',
        :'merchant_agreement_url' => :'merchantAgreementUrl',
        :'merchant_redirect_url' => :'merchantRedirectUrl',
        :'price' => :'price',
        :'product_name' => :'productName',
        :'product_description' => :'productDescription',
        :'scope' => :'scope'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'campaign' => :'CampaignRequest',
        :'currency' => :'Currency',
        :'customer_phone_number' => :'String',
        :'initial_charge' => :'InitialCharge',
        :'interval' => :'Interval',
        :'interval_count' => :'Integer',
        :'is_app' => :'Boolean',
        :'merchant_agreement_url' => :'String',
        :'merchant_redirect_url' => :'String',
        :'price' => :'Integer',
        :'product_name' => :'String',
        :'product_description' => :'String',
        :'scope' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `VippsRecurring::AgreementRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `VippsRecurring::AgreementRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'campaign')
        self.campaign = attributes[:'campaign']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = 'NOK'
      end

      if attributes.key?(:'customer_phone_number')
        self.customer_phone_number = attributes[:'customer_phone_number']
      end

      if attributes.key?(:'initial_charge')
        self.initial_charge = attributes[:'initial_charge']
      end

      if attributes.key?(:'interval')
        self.interval = attributes[:'interval']
      else
        self.interval = 'MONTH'
      end

      if attributes.key?(:'interval_count')
        self.interval_count = attributes[:'interval_count']
      end

      if attributes.key?(:'is_app')
        self.is_app = attributes[:'is_app']
      end

      if attributes.key?(:'merchant_agreement_url')
        self.merchant_agreement_url = attributes[:'merchant_agreement_url']
      end

      if attributes.key?(:'merchant_redirect_url')
        self.merchant_redirect_url = attributes[:'merchant_redirect_url']
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'product_name')
        self.product_name = attributes[:'product_name']
      end

      if attributes.key?(:'product_description')
        self.product_description = attributes[:'product_description']
      end

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if !@customer_phone_number.nil? && @customer_phone_number.to_s.length > 15
        invalid_properties.push('invalid value for "customer_phone_number", the character length must be smaller than or equal to 15.')
      end

      if @interval.nil?
        invalid_properties.push('invalid value for "interval", interval cannot be nil.')
      end

      if @interval_count.nil?
        invalid_properties.push('invalid value for "interval_count", interval_count cannot be nil.')
      end

      if @interval_count > 31
        invalid_properties.push('invalid value for "interval_count", must be smaller than or equal to 31.')
      end

      if @interval_count < 1
        invalid_properties.push('invalid value for "interval_count", must be greater than or equal to 1.')
      end

      if @is_app.nil?
        invalid_properties.push('invalid value for "is_app", is_app cannot be nil.')
      end

      if @merchant_agreement_url.nil?
        invalid_properties.push('invalid value for "merchant_agreement_url", merchant_agreement_url cannot be nil.')
      end

      if @merchant_redirect_url.nil?
        invalid_properties.push('invalid value for "merchant_redirect_url", merchant_redirect_url cannot be nil.')
      end

      if @price.nil?
        invalid_properties.push('invalid value for "price", price cannot be nil.')
      end

      if @price < 100
        invalid_properties.push('invalid value for "price", must be greater than or equal to 100.')
      end

      if @product_name.nil?
        invalid_properties.push('invalid value for "product_name", product_name cannot be nil.')
      end

      if @product_name.to_s.length > 45
        invalid_properties.push('invalid value for "product_name", the character length must be smaller than or equal to 45.')
      end

      if @product_description.nil?
        invalid_properties.push('invalid value for "product_description", product_description cannot be nil.')
      end

      if @product_description.to_s.length > 100
        invalid_properties.push('invalid value for "product_description", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @currency.nil?
      return false if !@customer_phone_number.nil? && @customer_phone_number.to_s.length > 15
      return false if @interval.nil?
      return false if @interval_count.nil?
      return false if @interval_count > 31
      return false if @interval_count < 1
      return false if @is_app.nil?
      return false if @merchant_agreement_url.nil?
      return false if @merchant_redirect_url.nil?
      return false if @price.nil?
      return false if @price < 100
      return false if @product_name.nil?
      return false if @product_name.to_s.length > 45
      return false if @product_description.nil?
      return false if @product_description.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_phone_number Value to be assigned
    def customer_phone_number=(customer_phone_number)
      if !customer_phone_number.nil? && customer_phone_number.to_s.length > 15
        fail ArgumentError, 'invalid value for "customer_phone_number", the character length must be smaller than or equal to 15.'
      end

      @customer_phone_number = customer_phone_number
    end

    # Custom attribute writer method with validation
    # @param [Object] interval_count Value to be assigned
    def interval_count=(interval_count)
      if interval_count.nil?
        fail ArgumentError, 'interval_count cannot be nil'
      end

      if interval_count > 31
        fail ArgumentError, 'invalid value for "interval_count", must be smaller than or equal to 31.'
      end

      if interval_count < 1
        fail ArgumentError, 'invalid value for "interval_count", must be greater than or equal to 1.'
      end

      @interval_count = interval_count
    end

    # Custom attribute writer method with validation
    # @param [Object] price Value to be assigned
    def price=(price)
      if price.nil?
        fail ArgumentError, 'price cannot be nil'
      end

      if price < 100
        fail ArgumentError, 'invalid value for "price", must be greater than or equal to 100.'
      end

      @price = price
    end

    # Custom attribute writer method with validation
    # @param [Object] product_name Value to be assigned
    def product_name=(product_name)
      if product_name.nil?
        fail ArgumentError, 'product_name cannot be nil'
      end

      if product_name.to_s.length > 45
        fail ArgumentError, 'invalid value for "product_name", the character length must be smaller than or equal to 45.'
      end

      @product_name = product_name
    end

    # Custom attribute writer method with validation
    # @param [Object] product_description Value to be assigned
    def product_description=(product_description)
      if product_description.nil?
        fail ArgumentError, 'product_description cannot be nil'
      end

      if product_description.to_s.length > 100
        fail ArgumentError, 'invalid value for "product_description", the character length must be smaller than or equal to 100.'
      end

      @product_description = product_description
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          campaign == o.campaign &&
          currency == o.currency &&
          customer_phone_number == o.customer_phone_number &&
          initial_charge == o.initial_charge &&
          interval == o.interval &&
          interval_count == o.interval_count &&
          is_app == o.is_app &&
          merchant_agreement_url == o.merchant_agreement_url &&
          merchant_redirect_url == o.merchant_redirect_url &&
          price == o.price &&
          product_name == o.product_name &&
          product_description == o.product_description &&
          scope == o.scope
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [campaign, currency, customer_phone_number, initial_charge, interval, interval_count, is_app, merchant_agreement_url, merchant_redirect_url, price, product_name, product_description, scope].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = VippsRecurring.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
