=begin
#Recurring Payments Merchant API

## Recurring payments Recurring payments is used for subscription payments such as weekly dues for newspaper access, monthly dues for public transportation, etc. 1. A draft agreement is initialized and the user is redirected for approval. 2. The user approves the agreement and the merchant can call GET on the agreement to verify the status. 3. The merchant can start sending charges which will be charged the user in the future. The merchant is responsible for checking the status of charges, and cancelling any user access if charges are failing (or contacting the user). ## Authentication See <a href=\"#/Access%20Controller/getAccessToken\" target=\"_blank\">Get Access Token</a> For information regarding authentication please read [our guide](https://github.com/vippsas/vipps-recurring-api/blob/master/vipps-recurring-api.md#authentication-and-authorization---api-access-token)

The version of the OpenAPI document: 2.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for VippsRecurring::AccessControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccessControllerApi' do
  before do
    # run before each test
    @api_instance = VippsRecurring::AccessControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccessControllerApi' do
    it 'should create an instance of AccessControllerApi' do
      expect(@api_instance).to be_instance_of(VippsRecurring::AccessControllerApi)
    end
  end

  # unit tests for get_access_token
  # Get Access Token
  # @param client_id Provided Client ID
  # @param client_secret Provided Client Secret
  # @param ocp_apim_subscription_key The subscription key for your API product is available on portal.vipps.no, under the &#39;Utvikler&#39; tab. Keep it secret.
  # @param [Hash] opts the optional parameters
  # @return [AccessTokenResponse]
  describe 'get_access_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
